server:  
  port: ${PORT:2222}
spring:  
  application:
    name: account-service
  cloud:
    config:
      uri : http://localhost:8090
  boot:
    admin:
      client:
        url: http://localhost:7777/
ribbon:
  eureka:
    enabled: true